# -*- coding: utf-8 -*-
"""4_앙상블_랜덤포레스트_과일종류맞추기_최종.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cRxog5mbnpR5nce3EGLpoK4aCbQ2WGg7
"""

#Step 1. 구글 코랩에 한글 폰트 설정하기

!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

#Step 2.분석할 데이터가 저장된 파일을 불러와서 변수에 할당합니다.
from google.colab import files
myfile = files.upload()
import io
import pandas as pd
#pd.read_csv로 csv파일 불러오기
과일채소목록 = pd.read_csv(io.BytesIO(myfile['과일채소목록.csv']),
                       encoding='cp949')
과일채소목록

#Step 3. 훈련용 세트와 테스트용 세트로 나눕니다.
data = 과일채소목록[ ['무게_g','길이_cm','색상','당도']] 
target = 과일채소목록['종류']

from sklearn.model_selection import train_test_split
훈련용_data , 테스트용_data , 훈련용_target , 테스트용_target = train_test_split(
    data , target , test_size=0.3 , random_state=40)

print(훈련용_data)

print(훈련용_target)

print(훈련용_data.shape , 테스트용_data.shape)

from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=10, n_jobs=-1 , random_state=40)
rf.fit(훈련용_data , 훈련용_target)

rf.score(테스트용_data , 테스트용_target)

rf.predict(테스트용_data)

테스트용_data

예측결과 = pd.DataFrame(rf.predict(테스트용_data), columns=['예측결과'])
result = pd.concat([테스트용_data.reset_index(drop=True), 예측결과], axis=1)
result

import numpy as np
from sklearn.model_selection import cross_validate

scores= cross_validate(rf , 훈련용_data , 훈련용_target,
                       return_train_score=True , n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

import matplotlib.pyplot as plt
plt.rc('font', family='NanumBarunGothic') 

imp = rf.feature_importances_
print('중요속성지표값:',imp)

plt.figure()
plt.bar(range(len(imp)),imp)
plt.xticks(range(len(imp)),data.columns, rotation=90)
plt.show()

